language: python

python:
  - "3.7"

# command to install dependencies
install:
  - python setup.py install

# command to run tests
script:
  - pytest


notifications:
  slack:
    rooms:
	  - foxytrixy:HZwjgEulu0umNtMJ1E9UhGPA#foxylib