language: python

python:
- 3.7.5

install:
- python setup.py install

script:
- pytest --cov=foxylib/

notifications:
  slack: foxytrixy:HZwjgEulu0umNtMJ1E9UhGPA#foxylib

after_success:
- coveralls

before_install:
- mkdir -p env/googleapi
- openssl aes-256-cbc -K $encrypted_5753cc0d79af_key -iv $encrypted_5753cc0d79af_iv
  -in env-travis/googleapi/foxylib-ff3a87675bbe.json.enc -out env/googleapi/foxylib-ff3a87675bbe.json
  -d
