swagger: '2.0'
info:
  title: foxytrixy foxylib
  version: "0.1.0"
consumes:
  - application/json
produces:
  - application/json

#security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
#  - oauth2: [uid]

paths:
  /health_liveness:
    get:
      tags: [healthcheck liveness]
      operationId: foxylib.tools.flask.foxylib_flask.FoxylibFront.health_liveness
      summary: Return a 200 status if health check is successful
      responses:
        200:
          description: Liveness Health check is successful
        404:
          description: Not Found

  /health_readiness:
    get:
      tags: [healthcheck readiness]
      operationId: foxylib.tools.flask.foxylib_flask.FoxylibFront.health_readiness
      summary: Return a 200 status if health check is successful
      responses:
        200:
          description: Readiness Health check is successful
        404:
          description: Not Found


securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
